-- FEASTERVILLE POS V105 — Internal inventory transfers between stores

create sequence if not exists public.pos_inventory_transfer_ref_seq;

create table if not exists public.pos_inventory_transfers (
  id bigint generated by default as identity primary key,
  transfer_ref text not null unique default (
    'TRF-' || to_char(current_date,'YYYYMMDD') || '-' ||
    lpad(nextval('public.pos_inventory_transfer_ref_seq'::regclass)::text,6,'0')
  ),
  transfer_date date not null default current_date,
  from_store text not null references public.pos_stores(code),
  to_store text not null references public.pos_stores(code),
  item_type text not null default 'PRODUCTION_INPUT' check (item_type='PRODUCTION_INPUT'),
  item_code text not null,
  item_name text not null,
  unit text not null default 'EA',
  qty numeric not null check (qty > 0),
  unit_cost numeric not null default 0 check (unit_cost >= 0),
  status text not null default 'PENDING' check (status in ('PENDING','RECEIVED','CANCELLED')),
  notes text,
  created_by uuid not null references auth.users(id),
  created_by_name text,
  created_at timestamptz not null default now(),
  received_by uuid references auth.users(id),
  received_by_name text,
  received_at timestamptz,
  cancelled_by uuid references auth.users(id),
  cancelled_by_name text,
  cancelled_at timestamptz,
  constraint pos_inventory_transfers_different_stores check (from_store <> to_store)
);

create index if not exists pos_inventory_transfers_from_idx on public.pos_inventory_transfers(from_store,transfer_date desc);
create index if not exists pos_inventory_transfers_to_idx on public.pos_inventory_transfers(to_store,transfer_date desc);
create index if not exists pos_inventory_transfers_status_idx on public.pos_inventory_transfers(status,transfer_date desc);
create index if not exists pos_inventory_transfers_item_idx on public.pos_inventory_transfers(item_code,transfer_date desc);

alter table public.pos_inventory_transfers enable row level security;

revoke all on table public.pos_inventory_transfers from anon;
revoke insert, update, delete on table public.pos_inventory_transfers from authenticated;
grant select on table public.pos_inventory_transfers to authenticated;

-- Managers can view every transfer.
drop policy if exists pos_inventory_transfers_manager_select on public.pos_inventory_transfers;
create policy pos_inventory_transfers_manager_select
on public.pos_inventory_transfers for select to authenticated
using (
  exists (
    select 1 from public.pos_profiles p
    where p.user_id=(select auth.uid()) and p.role='manager' and coalesce(p.active,true)
  )
);

-- Inventory controllers can view transfers sent from or received by their assigned store.
drop policy if exists pos_inventory_transfers_inventory_control_select on public.pos_inventory_transfers;
create policy pos_inventory_transfers_inventory_control_select
on public.pos_inventory_transfers for select to authenticated
using (
  exists (
    select 1 from public.pos_profiles p
    where p.user_id=(select auth.uid())
      and p.role='inventory_control'
      and coalesce(p.active,true)
      and p.store_code in (pos_inventory_transfers.from_store,pos_inventory_transfers.to_store)
  )
);

create or replace function public.pos_create_inventory_transfer(
  p_from_store text,
  p_to_store text,
  p_item_code text,
  p_qty numeric,
  p_notes text default null
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_role text;
  v_user_store text;
  v_user_name text;
  v_item_name text;
  v_unit text;
  v_dest_unit text;
  v_available numeric := 0;
  v_cost numeric := 0;
  v_transfer public.pos_inventory_transfers%rowtype;
begin
  if v_uid is null then raise exception 'Authentication required.'; end if;
  if p_from_store is null or p_to_store is null or p_from_store=p_to_store then
    raise exception 'Select two different stores.';
  end if;
  if p_item_code is null or btrim(p_item_code)='' then raise exception 'Select an inventory item.'; end if;
  if p_qty is null or p_qty<=0 then raise exception 'Transfer quantity must be greater than zero.'; end if;

  select lower(p.role), p.store_code, coalesce(p.display_name,'User')
    into v_role,v_user_store,v_user_name
  from public.pos_profiles p
  where p.user_id=v_uid and coalesce(p.active,true)
  limit 1;

  if v_role not in ('manager','inventory_control') then raise exception 'Manager or Inventory Controller access required.'; end if;
  if v_role='inventory_control' and v_user_store is distinct from p_from_store then
    raise exception 'Inventory Controller can only dispatch stock from the assigned store.';
  end if;

  if not exists(select 1 from public.pos_stores s where s.code=p_from_store and s.active=true) then raise exception 'Sending store is not active.'; end if;
  if not exists(select 1 from public.pos_stores s where s.code=p_to_store and s.active=true) then raise exception 'Receiving store is not active.'; end if;

  select i.name, coalesce(i.unit,'EA') into v_item_name,v_unit
  from public.pos_store_production_inputs i
  where i.store_code=p_from_store and i.code=p_item_code and i.active=true
  limit 1;
  if v_item_name is null then raise exception 'Item is not an active Production Input at the sending store.'; end if;

  select coalesce(i.unit,'EA') into v_dest_unit
  from public.pos_store_production_inputs i
  where i.store_code=p_to_store and i.code=p_item_code and i.active=true
  limit 1;
  if v_dest_unit is null then raise exception 'Item must first be added as an active Production Input at the receiving store.'; end if;
  if upper(coalesce(v_unit,'')) <> upper(coalesce(v_dest_unit,'')) then
    raise exception 'Unit mismatch between stores (% vs %). Correct the Production Input units before transfer.',v_unit,v_dest_unit;
  end if;

  select coalesce(c.opening_qty,0)+coalesce(c.received_qty,0)-coalesce(c.used_qty,0)
  into v_available
  from public.pos_store_input_counts c
  where c.store_code=p_from_store and c.input_code=p_item_code and c.count_date=current_date
  limit 1;
  if not found then
    v_available := public.previous_input_closing(p_from_store,p_item_code,current_date);
  end if;
  v_available := coalesce(v_available,0);
  if p_qty > v_available then
    raise exception 'Insufficient stock. Available quantity is % %.',round(v_available,3),v_unit;
  end if;

  select coalesce(sum(r.qty*r.unit_cost)/nullif(sum(r.qty),0),0)
    into v_cost
  from public.pos_stock_receipts r
  where r.store_code=p_from_store and r.input_code=p_item_code
    and r.receipt_date<=current_date and r.qty>0 and r.unit_cost>0;
  if coalesce(v_cost,0)=0 then
    select coalesce(i.preferred_unit_cost,0) into v_cost
    from public.pos_store_production_inputs i
    where i.store_code=p_from_store and i.code=p_item_code
    limit 1;
  end if;

  insert into public.pos_inventory_transfers(
    from_store,to_store,item_code,item_name,unit,qty,unit_cost,notes,created_by,created_by_name
  ) values (
    p_from_store,p_to_store,p_item_code,v_item_name,v_unit,p_qty,coalesce(v_cost,0),nullif(btrim(coalesce(p_notes,'')),''),v_uid,v_user_name
  ) returning * into v_transfer;

  -- Negative receipt = internal stock-out. Existing receipt trigger updates the source stock count.
  insert into public.pos_stock_receipts(
    receipt_date,supplier,reference,input_code,input_name,unit,qty,unit_cost,received_by,created_by,store_code
  ) values (
    current_date,'INTERNAL TRANSFER OUT TO '||p_to_store,v_transfer.transfer_ref,p_item_code,v_item_name,v_unit,-p_qty,coalesce(v_cost,0),v_user_name,v_uid,p_from_store
  );

  return to_jsonb(v_transfer);
end;
$$;

create or replace function public.pos_receive_inventory_transfer(p_transfer_ref text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_role text;
  v_user_store text;
  v_user_name text;
  v_transfer public.pos_inventory_transfers%rowtype;
begin
  if v_uid is null then raise exception 'Authentication required.'; end if;
  select lower(p.role), p.store_code, coalesce(p.display_name,'User')
    into v_role,v_user_store,v_user_name
  from public.pos_profiles p
  where p.user_id=v_uid and coalesce(p.active,true)
  limit 1;
  if v_role not in ('manager','inventory_control') then raise exception 'Manager or Inventory Controller access required.'; end if;

  select * into v_transfer
  from public.pos_inventory_transfers t
  where t.transfer_ref=p_transfer_ref
  for update;
  if not found then raise exception 'Transfer not found.'; end if;
  if v_transfer.status<>'PENDING' then raise exception 'Only a pending transfer can be received.'; end if;
  if v_role='inventory_control' and v_user_store is distinct from v_transfer.to_store then
    raise exception 'Inventory Controller can only receive stock for the assigned store.';
  end if;
  if not exists(select 1 from public.pos_store_production_inputs i where i.store_code=v_transfer.to_store and i.code=v_transfer.item_code and i.active=true) then
    raise exception 'The item is no longer active at the receiving store.';
  end if;

  insert into public.pos_stock_receipts(
    receipt_date,supplier,reference,input_code,input_name,unit,qty,unit_cost,received_by,created_by,store_code
  ) values (
    current_date,'INTERNAL TRANSFER IN FROM '||v_transfer.from_store,v_transfer.transfer_ref,v_transfer.item_code,v_transfer.item_name,v_transfer.unit,v_transfer.qty,v_transfer.unit_cost,v_user_name,v_uid,v_transfer.to_store
  );

  update public.pos_inventory_transfers
  set status='RECEIVED',received_by=v_uid,received_by_name=v_user_name,received_at=now()
  where id=v_transfer.id
  returning * into v_transfer;
  return to_jsonb(v_transfer);
end;
$$;

create or replace function public.pos_cancel_inventory_transfer(p_transfer_ref text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_role text;
  v_user_store text;
  v_user_name text;
  v_transfer public.pos_inventory_transfers%rowtype;
begin
  if v_uid is null then raise exception 'Authentication required.'; end if;
  select lower(p.role), p.store_code, coalesce(p.display_name,'User')
    into v_role,v_user_store,v_user_name
  from public.pos_profiles p
  where p.user_id=v_uid and coalesce(p.active,true)
  limit 1;
  if v_role not in ('manager','inventory_control') then raise exception 'Manager or Inventory Controller access required.'; end if;

  select * into v_transfer
  from public.pos_inventory_transfers t
  where t.transfer_ref=p_transfer_ref
  for update;
  if not found then raise exception 'Transfer not found.'; end if;
  if v_transfer.status<>'PENDING' then raise exception 'Only a pending transfer can be cancelled.'; end if;
  if v_role='inventory_control' and v_user_store is distinct from v_transfer.from_store then
    raise exception 'Inventory Controller can only cancel a transfer dispatched from the assigned store.';
  end if;

  -- Reverse the dispatch stock-out at the source store.
  insert into public.pos_stock_receipts(
    receipt_date,supplier,reference,input_code,input_name,unit,qty,unit_cost,received_by,created_by,store_code
  ) values (
    current_date,'INTERNAL TRANSFER CANCELLATION',v_transfer.transfer_ref||'-CANCEL',v_transfer.item_code,v_transfer.item_name,v_transfer.unit,v_transfer.qty,v_transfer.unit_cost,v_user_name,v_uid,v_transfer.from_store
  );

  update public.pos_inventory_transfers
  set status='CANCELLED',cancelled_by=v_uid,cancelled_by_name=v_user_name,cancelled_at=now()
  where id=v_transfer.id
  returning * into v_transfer;
  return to_jsonb(v_transfer);
end;
$$;

revoke execute on function public.pos_create_inventory_transfer(text,text,text,numeric,text) from public, anon;
revoke execute on function public.pos_receive_inventory_transfer(text) from public, anon;
revoke execute on function public.pos_cancel_inventory_transfer(text) from public, anon;
grant execute on function public.pos_create_inventory_transfer(text,text,text,numeric,text) to authenticated;
grant execute on function public.pos_receive_inventory_transfer(text) to authenticated;
grant execute on function public.pos_cancel_inventory_transfer(text) to authenticated;
