-- V107 Store Operating Expenses
create table if not exists public.pos_store_operating_expenses (
  id bigint generated by default as identity primary key,
  store_code text not null check (store_code in ('NDAYENI','SIVANA','BIRCH_ACRES')),
  expense_date date not null default current_date,
  category text not null,
  amount numeric(14,2) not null check (amount > 0),
  payment_method text not null check (payment_method in ('Business Bank/Card','Outside Cash','Cash Drawer','Owner/Personal Funds')),
  supplier_payee text,
  reference text,
  notes text,
  created_by uuid not null default auth.uid(),
  created_at timestamptz not null default now()
);
alter table public.pos_store_operating_expenses enable row level security;
drop policy if exists store_operating_expenses_manager_all on public.pos_store_operating_expenses;
create policy store_operating_expenses_manager_all on public.pos_store_operating_expenses
for all to authenticated
using (exists (select 1 from public.pos_profiles p where p.user_id=(select auth.uid()) and lower(p.role)='manager' and coalesce(p.active,true)))
with check (exists (select 1 from public.pos_profiles p where p.user_id=(select auth.uid()) and lower(p.role)='manager' and coalesce(p.active,true)));
create index if not exists idx_pos_store_operating_expenses_store_date on public.pos_store_operating_expenses(store_code, expense_date);
