-- V106 Banking & Owner Funds Control
create table if not exists public.pos_owner_drawings (
  id bigint generated by default as identity primary key, store_code text not null, drawing_date date not null default current_date, amount numeric(14,2) not null check (amount > 0), payment_method text not null default 'Cash', purpose text, reference text, created_by uuid not null default auth.uid(), created_at timestamptz not null default now());
create table if not exists public.pos_sales_settlements (
  id bigint generated by default as identity primary key, store_code text not null, sales_date date not null, source text not null check (source in ('Cash','Card','Mr D','Uber Eats')), settlement_date date not null default current_date, gross_amount numeric(14,2) not null check (gross_amount >= 0), fees numeric(14,2) not null default 0 check (fees >= 0), net_amount numeric(14,2) generated always as (gross_amount-fees) stored, reference text, notes text, created_by uuid not null default auth.uid(), created_at timestamptz not null default now());
-- Manager-only RLS policies are applied in live migration banking_owner_drawings_control_v106.
